[package]
name = "client"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[features]
default = ["rodio_audio"]
rodio_audio = []

[dependencies]
encoding_rs = "0.8.20"
client-api = { git = "https://github.com/zottce/samp-client-api.git", rev = "b2f1737" }
cef = { path = "../cef" }
cef-sys = { path = "../cef-sys" }
crossbeam-channel = "0.3.9"
d3dx9 = { path = "../d3dx9" }
winapi = { version = "0.3.8", features = ["d3d9", "winuser", "libloaderapi", "winver", "consoleapi", "memoryapi", "shlobj"] }
laminar = "0.3.2"
messages = { path = "../messages" }
quick-protobuf = "0.7.0"
detour = "0.7.1"
libloading = "0.5.2"
alto = "3.0.4"
log = "0.4.14"
simplelog = "0.9.0"
ambisonic = "0.4.1"
nalgebra = "0.24.1"
parking_lot = "0.11.1"
