[package]
name = "client"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
encoding_rs = "0.8.20"
client-api = { path = "../../client-api" }
cef = { path = "../cef" }
cef-sys = { path = "../cef-sys" }
crossbeam-channel = "0.3.9"
d3dx9 = { path = "../../../d3dx9" }
winapi = { version = "0.3.8", features = ["d3d9", "winuser", "libloaderapi", "winver", "consoleapi", "memoryapi"] }
laminar = "0.3.2"
messages = { path = "../messages" }
quick-protobuf = "0.6.3"
detour = "0.7.1"
libloading = "0.5.2"
alto = "3.0.4"