[workspace]
members = [
    "cef-sys",
    "cef",
    "loader",
    "client",
    "renderer",
    "messages",
    "server",
    "cef-tests",
]

default-members = [
    "loader",
    "client",
    "renderer",
    "server",
]

[profile.release]
lto = true
