[workspace]
members = [
    "cef-sys",
    "cef",
    "loader",
    "client",
    "renderer",
    "messages",
    "server",
    "cef-api",
    "cef-interface",
]

[profile.release]
lto = true
